---
- name: 
  hosts: Server_2019
  gather_facts: no 
  
  tasks:
    - name: Creating directory for site
      ansible.windows.win_file:
        path: C:\Temp\iis_site
        state: directory

    - name: Creating WebSite
      community.windows.win_iis_website:
        name: user0{{ item }}
        port: 10{{ item }}
        physical_path: C:\Temp\iis_site
      loop: "{{ range(1,10) | list }}"

    - name: Creating WebSite
      community.windows.win_iis_website:
        name: user{{ item }}
        port: 1{{ item }}
        physical_path: C:\Temp\iis_site
      loop: "{{ range(10,51) | list }}"      