---
- name: Create 50 users
  hosts: Server_2019
  gather_facts: no

  tasks: 
    - name: Create Users
      win_command: NET USER user0{{ item }} 'user{{ item }}' /ADD
      loop: "{{ range(1,10) | list }}"

    - name: Create Users
      win_command: NET USER user{{ item }} 'user{{ item }}' /ADD
      loop: "{{ range(10,51) | list }}"